version: '3.3'

services:
  demo-vue:
    image: demo-vue:lts
    ports:
      - 8788:8080
      - 6005:5005
    container_name: demo-vue
    volumes:
      - ./web-variables.env:/web-variables.env
    env_file:
      - web-variables.env
    extra_hosts:
      - "site.mongo.com:172.17.0.1"
      - "site.mysql.com:172.17.0.1"
      - "site.redis.com:172.17.0.1"
      - "jaeger-agent.nexusguard.asia:10.6.5.225"
    entrypoint:
      - java
      - -Djava.security.edg=file:/dev/./urandom
      - -jar
      - /app.jar
      - --spring.profiles.active=dev
#  site-cp:
#    image: site-cp:lts
#    ports:
#    - 8001:80
#    container_name: site-cp
#    extra_hosts:
#      - "demo-vue.site.net:172.17.0.1"


